FROM gradle:4.2.1-jdk8-alpine
WORKDIR /app
COPY ./ /app

USER root
RUN chown -R gradle /app
USER gradle

RUN ./gradlew build --stacktrace

VOLUME /tmp
ADD build/libs/spring-kotlin-session-0.0.1-SNAPSHOT.jar spring-kotlin-session.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/spring-kotlin-session.jar"]